theme: jekyll-theme-cayman
title: Guia Financeiro e Ético para Carreiras em Computação
description: Um recurso completo para estudantes e profissionais de computação que desejam tomar decisões informadas sobre carreira